### ISSUE TITLE
semi colon required

### ISSUE THREAD

**Issue by pacostas** [nodeshift-starters/bdi#14]
https://github.com/nodeshift-starters/bdi/blob/eea11d25f67eb1b215e3e50632d115b248634c29/package.json#L27

I think you can deprecate eslint-config-semistandard by setting proper settings in eslint rules https://eslint.org/docs/latest/rules/semi

**Comment by helio-frota** [comment]
@pacostas cool, interested in sending a PR for this? thanks

**Comment by pacostas** [comment]
@helio-frota  Opened PR https://github.com/nodeshift-starters/bdi/pull/20

**Comment by helio-frota** [comment]
great thanks!
